import crypto from "node:crypto";
import { prisma } from "./prisma";
import type { SyncResult } from "./graph";

/**
 * Synthetic email source for dev mode.
 *
 * Used by syncEmails() when the signed-in user has no linked Microsoft
 * account (i.e. they signed in via /api/dev/signin). It seeds a stable
 * starter inbox on the first run, and adds a fresh "Sync run at …"
 * message on every subsequent sync so the UI noticeably updates.
 */
const SAMPLE_INBOX: Array<{
  subject: string;
  fromName: string;
  fromEmail: string;
  snippet: string;
  bodyPreview: string;
  hoursAgo: number;
}> = [
  {
    subject: "Welcome to Emailyzer 👋",
    fromName: "Emailyzer Team",
    fromEmail: "hello@emailyzer.local",
    snippet:
      "Thanks for trying Emailyzer! You're currently signed in as a dev user.",
    bodyPreview:
      "Thanks for trying Emailyzer!\n\nYou're currently signed in as a dev user. " +
      "When you wire up a real Microsoft Entra ID app and set ENABLE_DEV_AUTH=false, " +
      "Sync now will pull from your real Outlook inbox via Microsoft Graph.\n\n" +
      "— The Emailyzer Team",
    hoursAgo: 1,
  },
  {
    subject: "Your weekly digest",
    fromName: "Acme Newsletter",
    fromEmail: "digest@acme.example",
    snippet:
      "This week: 3 new product launches, a deep dive on observability, and an event invite.",
    bodyPreview:
      "Hi there,\n\nThis week we shipped three new things, wrote a deep dive on " +
      "observability for distributed systems, and we'd love to see you at our meetup.\n\n" +
      "Cheers,\nAcme",
    hoursAgo: 5,
  },
  {
    subject: "Re: Q3 roadmap review",
    fromName: "Priya Singh",
    fromEmail: "priya@acme.example",
    snippet:
      "Great call earlier — I've attached the updated roadmap deck. Let me know if anything looks off.",
    bodyPreview:
      "Hi,\n\nGreat call earlier. I've attached the updated Q3 roadmap deck — let me " +
      "know if you spot anything missing before we share it more broadly tomorrow.\n\n" +
      "Thanks,\nPriya",
    hoursAgo: 26,
  },
  {
    subject: "Your invoice #INV-2031 is ready",
    fromName: "Billing",
    fromEmail: "billing@vendor.example",
    snippet:
      "Invoice #INV-2031 for $1,240.00 is now available. Payment is due in 14 days.",
    bodyPreview:
      "Hello,\n\nInvoice #INV-2031 in the amount of $1,240.00 is now available. " +
      "Payment is due within 14 days. You can view the invoice in your account.\n\n" +
      "— Billing",
    hoursAgo: 48,
  },
  {
    subject: "Security alert: new sign-in on Windows",
    fromName: "Account Security",
    fromEmail: "no-reply@security.example",
    snippet:
      "We noticed a new sign-in to your account from a Windows device. Was this you?",
    bodyPreview:
      "We noticed a new sign-in from a Windows device in Seattle, WA.\n\n" +
      "If this was you, you can ignore this message. If not, please secure your account.",
    hoursAgo: 72,
  },
];

export async function syncMockEmails(userId: string): Promise<SyncResult> {
  const existing = await prisma.email.count({ where: { userId } });
  let upserted = 0;

  if (existing === 0) {
    for (const sample of SAMPLE_INBOX) {
      const receivedAt = new Date(
        Date.now() - sample.hoursAgo * 60 * 60 * 1000,
      );
      const messageId = `mock-${crypto
        .createHash("sha1")
        .update(`${userId}:${sample.subject}:${sample.fromEmail}`)
        .digest("hex")}`;
      await prisma.email.upsert({
        where: { userId_messageId: { userId, messageId } },
        create: {
          userId,
          messageId,
          subject: sample.subject,
          fromEmail: sample.fromEmail,
          fromName: sample.fromName,
          receivedAt,
          snippet: sample.snippet,
          bodyPreview: sample.bodyPreview,
        },
        update: {},
      });
      upserted += 1;
    }
  } else {
    const stamp = new Date();
    const messageId = `mock-sync-${stamp.getTime()}`;
    await prisma.email.create({
      data: {
        userId,
        messageId,
        subject: `Sync ran at ${stamp.toLocaleTimeString()}`,
        fromEmail: "sync@emailyzer.local",
        fromName: "Emailyzer Sync",
        receivedAt: stamp,
        snippet:
          "This synthetic message proves that Sync now wrote new rows for your dev user.",
        bodyPreview:
          "This message was generated by the dev-mode mock Graph source. " +
          "In production, Sync now calls /me/mailFolders/Inbox/messages/delta on " +
          "Microsoft Graph and stores the resulting messages here.",
      },
    });
    upserted = 1;
  }

  await prisma.syncState.upsert({
    where: { userId },
    create: { userId, deltaToken: null, lastSyncedAt: new Date() },
    update: { lastSyncedAt: new Date() },
  });

  return { upserted, removed: 0, pages: 1, deltaTokenAdvanced: true };
}
